FROM python:3.12-slim

ARG POETRY_VERSION=1.8.2

# Set working directory
WORKDIR /code

COPY pyproject.toml poetry.lock README.md ./

COPY src/ ./src
COPY app/ ./app

RUN pip3 install --no-cache-dir poetry==${POETRY_VERSION} \ 
    && poetry env use 3.12

RUN poetry install --no-dev --with frontend --no-interaction --no-ansi

EXPOSE 80 8501

CMD ["poetry", "run", "streamlit", "run", "app/main.py", "--server.port", "8501", "--server.address", "0.0.0.0", "&", "poetry", "run", "uvicorn", "src.predict:app", "--host", "0.0.0.0", "--port", "80"]
