[tool.poetry]
name = "final project"
version = "0.1.0"
description = ""
authors = ["Ana Belen Barbero <anabarberocastejon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
pandas = "^2.2.3"
kagglehub = "^0.3.6"
scikit-learn = "^1.6.0"
sdv = "^1.17.3"
ipykernel = "^6.29.5"
seaborn = "^0.13.2"
ydata-profiling = "^4.12.1"
ipywidgets = "^8.1.5"
xgboost = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
