[tool.poetry]
name = "final project"
version = "0.1.0"
description = ""
authors = ["Ana Belen Barbero <anabarberocastejon@gmail.com>"]
readme = "README.md"
packages = [
    { include = "src" }
]


[tool.poetry.dependencies]
python = "~3.12"
pandas = "^2.2.3"
kagglehub = "^0.3.6"
scikit-learn = "^1.6.0"
sdv = "^1.17.3"
ipykernel = "^6.29.5"
seaborn = "^0.13.2"
ydata-profiling = "^4.12.1"
ipywidgets = "^8.1.5"
xgboost = "^2.1.3"
fastapi = {extras = ["standard"], version = "^0.115.6"}
imblearn = "^0.0"
pyarrow = "^18.1.0"
huggingface-hub = "^0.27.0"
transformers = {extras = ["torch"], version = "^4.47.1"}
evaluate = "^0.4.3"
python-dotenv = "^1.0.1"
nltk = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
