FROM python:3.12-slim

ARG POETRY_VERSION=1.8.2

# Set working directory
WORKDIR /code

COPY pyproject.toml poetry.lock README.md ./
COPY .env ./

COPY src/ ./src
COPY app/ ./app

RUN pip3 install --no-cache-dir poetry==${POETRY_VERSION} \ 
    && poetry env use 3.12

# main and frontend
RUN poetry install --without dev --no-interaction --no-ansi

EXPOSE 80 8501

COPY start_w_frontend.sh ./
RUN chmod +x start_w_frontend.sh

CMD ["./start_w_frontend.sh"]